#!/system/bin/sh
L="log -p i -t x1125io.initdlight"
CMD="/system/xbin/tor -f /sdcard/Backups/tor/torrc"
if ! ps|grep /system/xbin/tor|grep -v grep
then
  $L "*** Starting TOR: $CMD"
  exec $CMD
else
  $L "*** TOR is already running"
fi
