#!/system/bin/sh
L="log -p i -t x1125io.initdlight"
CMD="/system/bin/sshd -4 -p 8022"
if ! ps|grep bin/sshd|grep 8022|grep -v grep
then
    $L "*** Starting sshd: $CMD"
    exec $CMD
else
    $L "*** SSHD is already running on given port"
fi
