#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t x1125io.initdlight"
CMD="/system/xbin/i2pd \
      --service --daemon --datadir=/data/i2pd --conf=/sdcard/i2pd/i2pd.conf \
      --tunconf=/sdcard/i2pd/tunnels.conf --pidfile=/sdcard/i2pd/i2pd.pid"

if [ -f "/sdcard/i2pd/enabled" ]; then
  mkdir -p "/data/i2pd"
  if ! ps|grep /system/xbin/i2pd|grep -v grep
  then
    $L "*** Starting I2PD: $CMD"
    exec $CMD "$@"
  else
    $L "*** I2PD is already running"
  fi
fi
