#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t init.d"
CMD="/system/xbin/privoxy --no-daemon /sdcard/Backups/privoxy/privoxy.conf"
HTTP_PROXY="127.0.0.1:8228"
EXCLUSION_LIST="127.0.0.0/8,localhost"
settings put global http_proxy $HTTP_PROXY
settings put global http_proxy_exclusion_list $EXCLUSION_LIST
settings put global global_http_proxy_exclusion_list $EXCLUSION_LIST
$L "*** Set up global proxy variables:"
settings list global | grep proxy | while read line ; do $L $line ; done
$L "*** Starting Privoxy: $CMD"
start-stop-daemon -S -b -m -p /sdcard/Backups/privoxy/privoxy.pid -x /system/bin/logwrapper -- $CMD
